---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        ansible_user: root
verifier:
  name: ansible
  enabled: false
